FROM openjdk:11
ADD monitoring-service-0.0.1-SNAPSHOT.jar monitoring-service-0.0.1-SNAPSHOT.jar
ADD wait-for-it.sh wait-for-it.sh
RUN chmod +x /wait-for-it.sh
#ENTRYPOINT ["java", "-jar", "service-gateway-0.0.1-SNAPSHOT.jar"]
