
server:
    port: ${SERVER_PORT}

spring:
    application:
        name: monitoring
    security:
        user:
            name: "user"
            password: "password"

eureka:
    instance:
        leaseRenewalIntervalInSeconds: 10
        health-check-url-path: /actuator/health
        metadata-map:
            user.name: ${spring.security.user.name}        #These two are needed so that the server
            user.password: ${spring.security.user.password}
            startup: ${random.int}    #needed to trigger info and endpoint update after restart
    client:
        registryFetchIntervalSeconds: 5
        serviceUrl:
#            defaultZone: ${EUREKA-CLIENT-SERVICEURL-DEFAULTZONE}
            defaultZone: ${EUREKA_SERVICE_URL:http://discUser:discPassword@localhost:8761}/eureka/

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: ALWAYS
